# Generated by Django 3.0.1 on 2020-07-15 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0016_verifyemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyemail',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
