# Generated by Django 3.0.1 on 2020-07-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0019_auto_20200716_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='bestseller_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
