# Generated by Django 3.0.1 on 2020-07-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0020_bestseller_bestseller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
